In [1]:
l = [23, 7, -3]

In [2]:
print(l)

[23, 7, -3]


In [3]:
import numpy as np

In [4]:
a = np.array(l)

In [6]:
print(a)

[23  7 -3]


In [7]:
a

array([23,  7, -3])

In [8]:
b = np.array([5, True, 23.5, 'abc'])

In [9]:
b

array(['5', 'True', '23.5', 'abc'], dtype='<U32')

In [10]:
print(b)

['5' 'True' '23.5' 'abc']


In [11]:
l.pop()

-3

In [12]:
a.mean()

9.0

In [15]:
b1 = np.array([5, True, 23.5, False])

In [16]:
b1

array([ 5. ,  1. , 23.5,  0. ])

---

In [17]:
#SLicing

In [18]:
a

array([23,  7, -3])

In [19]:
a[2]

-3

In [20]:
a[0:2]

array([23,  7])

In [21]:
b = a[0:2]        #In array we are mapping as a view rather than another array(which happens in list)

In [22]:
b

array([23,  7])

In [23]:
b[0]

23

In [24]:
b[:] = 111

In [25]:
b

array([111, 111])

In [26]:
a

array([111, 111,  -3])

In [27]:
a[1] = 56

In [28]:
a

array([111,  56,  -3])

In [29]:
c = a.copy()      #to create a different array

In [30]:
c

array([111,  56,  -3])

In [31]:
c[0] = 0

In [32]:
c

array([ 0, 56, -3])

In [33]:
a

array([111,  56,  -3])